### ISSUE TITLE
Add a Jenkins template

### ISSUE THREAD

**Issue by adambiggs** [ericmatthys/grunt-changelog#1]
It would be really great if there was a preset template for building Jenkins compatible change logs: https://wiki.jenkins-ci.org/display/JENKINS/Change+log

**Comment by mischah** [comment]
@adambiggs Sorry, I can’t extract the needed format out of your link :confused:

**Comment by silkentrance** [comment]
@mischah With your latest changes, namely log arguments, this in part should be achievable.
However, since we are dealing with xml here, the change log cannot be build incrementally without adding XML support to grunt-changelog in order to insert the change elements into the document.

As for exact format, I think I managed to find it.... let me just look it up.

**Comment by mischah** [comment]
@silkentrance Thanks for your feedback :+1:
