### ISSUE TITLE
Node warning and RangeError

### ISSUE THREAD

**Issue by hstitz-jku** [ericmatthys/grunt-changelog#43]
Hi,
I installed this module as described  to my package.json: ```"grunt-changelog": "^0.3.0",```

Usage in Gruntfile.js:
```
    changelog: {
      sample: {
        options: {
        }
      }
    }
```

A run produces this console output:
```
(node) warning: Recursive process.nextTick detected. This will break in the next
 version of node. Please use setImmediate for recursive deferral.

util.js:35
  var str = String(f).replace(formatRegExp, function(x) {
                      ^
RangeError: Maximum call stack size exceeded
```

Does anyone has an idea what could be the problem here and how to solve it?

**Comment by mischah** [comment]
This one seems to come from [nodeunit](https://github.com/caolan/nodeunit) the dev dependency for our unit tests:

![Screenshot](http://f.cl.ly/items/343y223J0u2q0G3d2z3B/Bildschirmfoto%202015-02-06%20um%2014.45.19.png)

Please check if there is already an open [issue](https://github.com/caolan/nodeunit/issues) over there. Otherwise you should create an issue naming the nodejs version you’re are using.

**Comment by hstitz-jku** [comment]
Ok, thanks for your quick reply.

**Comment by mischah** [comment]
@hstitz-jku Your welcome :octocat:
